name: Selenium Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y libappindicator1 fonts-liberation
          sudo apt-get install -y google-chrome-stable

      - name: Setup ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oE "[0-9.]{10,20}" | cut -d '.' -f 1)
          echo "Detected Chrome version: $CHROME_VERSION"
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          echo "Detected ChromeDriver version: $CHROMEDRIVER_VERSION"
          wget -N "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" -P ~/
          unzip ~/chromedriver_linux64.zip -d ~/
          rm ~/chromedriver_linux64.zip
          sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
          sudo chown root:root /usr/local/bin/chromedriver
          sudo chmod 0755 /usr/local/bin/chromedriver

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest

      - name: Run Selenium Tests
        run: pytest tests/


